services:
  backend:
    # Tell Docker Compose to use the development Dockerfile
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    # Map your local backend folder into the container's /app folder
    volumes:
      - ./backend:/app
      # Use a named volume to persist node_modules inside the container,
      # preventing it from being overwritten by your local (potentially empty) node_modules.
      - /app/node_modules
    # Override the command to use nodemon for hot-reloading
    command: ["./scripts/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "dev"]
